name: santai_technician
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_background_service: ^2.0.0
  workmanager: ^0.5.1
  cupertino_icons: ^1.0.6
  device_info_plus: 10.1.2
  dropdown_search: 5.0.6
  flutter:
    sdk: flutter
  flutter_local_notifications: 17.2.2
  flutter_polyline_points: ^2.1.0
  flutter_secure_storage: 9.2.2
  flutter_timezone: ^3.0.1
  fluttertoast: 8.2.8 
  geocoding: 3.0.0
  geolocator: ^12.0.0
  get: 4.6.6
  google_maps_flutter: 2.10.0
  google_sign_in: 6.2.1
  http: ^1.2.2
  image_picker: 1.1.2
  intl: 0.19.0
  intl_phone_field: 3.2.0
  permission_handler: 11.3.1
  qr_code_scanner: 1.0.1
  shared_preferences: 2.3.2
  signalr_core: 1.1.2
  timeline_tile: 2.0.0
  timezone: 0.9.4
  uuid: ^4.5.1
  http_parser: ^4.0.2
  connectivity_plus: ^6.0.5
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.2.0
  firebase_messaging: ^15.1.2
  flutter_chat_types: 3.6.2
  flutter_chat_ui: 1.6.15
  sqflite: 2.3.3+1
  path: 1.9.0
  path_provider: ^2.0.14
  url_launcher: ^6.1.8
  flutter_markdown: ^0.7.4+3
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
dependency_overrides:
  web_socket_channel: ^2.4.3
  web: ^0.5.0
  
flutter:
  assets: 
    - assets/images/
    - assets/icons/
  fonts:
    - family: Saira
      fonts: 
        - asset: assets/fonts/sairas/Saira-Thin.ttf
          weight: 100
        - asset: assets/fonts/sairas/Saira-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sairas/Saira-Light.ttf
          weight: 300
        - asset: assets/fonts/sairas/Saira-Regular.ttf
          weight: 400
        - asset: assets/fonts/sairas/Saira-Medium.ttf
          weight: 500
        - asset: assets/fonts/sairas/Saira-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sairas/Saira-Bold.ttf
          weight: 700
        - asset: assets/fonts/sairas/Saira-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/sairas/Saira-Black.ttf
          weight: 900
    - family: SairaCondensed
      fonts:
        - asset: assets/fonts/sairas/Saira_Condensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/sairas/Saira_Condensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sairas/Saira_Condensed-Light.ttf
          weight: 300
        - asset: assets/fonts/sairas/Saira_Condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/sairas/Saira_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/sairas/Saira_Condensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sairas/Saira_Condensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/sairas/Saira_Condensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/sairas/Saira_Condensed-Black.ttf
          weight: 900
    - family: SairaSemiCondensed
      fonts:
        - asset: assets/fonts/sairas/Saira_SemiCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/sairas/Saira_SemiCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sairas/Saira_SemiCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/sairas/Saira_SemiCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/sairas/Saira_SemiCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/sairas/Saira_SemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sairas/Saira_SemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/sairas/Saira_SemiCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/sairas/Saira_SemiCondensed-Black.ttf
          weight: 900
    - family: SairaExtraCondensed
      fonts:
        - asset: assets/fonts/sairas/Saira_ExtraCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/sairas/Saira_ExtraCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sairas/Saira_ExtraCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/sairas/Saira_ExtraCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/sairas/Saira_ExtraCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/sairas/Saira_ExtraCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sairas/Saira_ExtraCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/sairas/Saira_ExtraCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/sairas/Saira_ExtraCondensed-Black.ttf
          weight: 900
    - family: SairaUltraCondensed
      fonts:
        - asset: assets/fonts/sairas/Saira_UltraCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/sairas/Saira_UltraCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sairas/Saira_UltraCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/sairas/Saira_UltraCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/sairas/Saira_UltraCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/sairas/Saira_UltraCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sairas/Saira_UltraCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/sairas/Saira_UltraCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/sairas/Saira_UltraCondensed-Black.ttf
          weight: 900
    - family: SairaExpanded
      fonts:
        - asset: assets/fonts/sairas/Saira_Expanded-Thin.ttf
          weight: 100
        - asset: assets/fonts/sairas/Saira_Expanded-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sairas/Saira_Expanded-Light.ttf
          weight: 300
        - asset: assets/fonts/sairas/Saira_Expanded-Regular.ttf
          weight: 400
        - asset: assets/fonts/sairas/Saira_Expanded-Medium.ttf
          weight: 500
        - asset: assets/fonts/sairas/Saira_Expanded-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sairas/Saira_Expanded-Bold.ttf
          weight: 700
        - asset: assets/fonts/sairas/Saira_Expanded-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/sairas/Saira_Expanded-Black.ttf
          weight: 900
  uses-material-design: true

flutter_launcher_icons:
  android: true  # Pastikan ini true untuk Android
  ios: true      # Pastikan ini true untuk iOS
  image_path: assets/images/logo_santaimoto_bluesquare.png  # Pastikan path ke gambar benar
  min_sdk_android: 21
  remove_alpha_ios: true
